// <auto-generated />
using Azure_Function_With_EFCore.DataContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Azure_Function_With_EFCore.Migrations
{
	[DbContext(typeof(FunctionContext))]
    partial class FunctionContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("AzureFunction_EFCore.Models.Album", b =>
                {
                    b.Property<int>("AlbumID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Anio")
                        .HasColumnType("int");

                    b.Property<int>("ArtistaID")
                        .HasColumnType("int");

                    b.Property<double>("Precio")
                        .HasColumnType("float");

                    b.Property<string>("Titulo")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AlbumID");

                    b.HasIndex("ArtistaID");

                    b.ToTable("Album");

                    b.HasData(
                        new
                        {
                            AlbumID = 1,
                            Anio = 1991,
                            ArtistaID = 2,
                            Precio = 180.0,
                            Titulo = "Romance"
                        },
                        new
                        {
                            AlbumID = 2,
                            Anio = 2017,
                            ArtistaID = 1,
                            Precio = 190.0,
                            Titulo = "Circo Soledad"
                        },
                        new
                        {
                            AlbumID = 3,
                            Anio = 2004,
                            ArtistaID = 3,
                            Precio = 210.0,
                            Titulo = "Aerosoul"
                        });
                });

            modelBuilder.Entity("AzureFunction_EFCore.Models.Artista", b =>
                {
                    b.Property<int>("ArtistaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Nombre")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ArtistaID");

                    b.ToTable("Artista");

                    b.HasData(
                        new
                        {
                            ArtistaID = 1,
                            Nombre = "Ricardo Arjona"
                        },
                        new
                        {
                            ArtistaID = 2,
                            Nombre = "Luis Miguel"
                        },
                        new
                        {
                            ArtistaID = 3,
                            Nombre = "Kalimba"
                        });
                });

            modelBuilder.Entity("AzureFunction_EFCore.Models.Album", b =>
                {
                    b.HasOne("AzureFunction_EFCore.Models.Artista", "Artista")
                        .WithMany()
                        .HasForeignKey("ArtistaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
